name: Generate badges

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read       # required to read repo
  pages: write         # required to deploy to Pages
  id-token: write      # required for Pages deployment

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: tinemf/badge-dev-test@v1
        with:
          output-dir: generated

      # 3️⃣ Deploy to GitHub Pages
      - name: Deploy to Pages
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          # the directory to deploy
          path: generated/
